MICRO_RENAME_MAP = {
    "V2003": "num_ordem",
    "V1016": "num_entrevista",
    "V1028": "peso",
    "posest": "estrato_pesquisa",
    "V1022": "zona",
    "V1023": "tipo_municipio",
    "V2005": "condicao_domicilio",
    "V2007": "sexo",
    "V2008": "dia_nasc",
    "V20081": "mes_nasc",
    "V20082": "ano_nasc",
    "V2009": "idade",
    "V2010": "raca_cor",
    "V3001": "sabe_ler_escrever",
    "V3002": "frequenta_escola",
    "V3002A": "rede_escola",
    "VD3004": "nivel_instrucao",
    "VD3005": "anos_estudo",
    "VD3006": "anos_estudo_faixa",
    "V2001": "num_moradores",
    "VD2002": "relacao_domicilio",
    "VD2003": "num_componentes_familia",
    "VD2004": "tipo_familia",
    "VD4001": "condicao_forca_trabalho",
    "VD4002": "condicao_ocupacao",
    "VD4003": "forca_trabalho_potencial",
    "VD4004": "subocupado_horas_efetivas",
    "VD4004A": "subocupado_horas_habituais",
    "VD4005": "desalentado",
    "VD4007": "posicao_empr_geral",
    "VD4008": "categoria_emprego",
    "VD4009": "posicao_emprego",
    "VD4010": "setor_atividade",
    "VD4011": "grupo_ocupacao",
    "VD4012": "contribui_previdencia",
    "V4012": "posicao_trab_principal",
    "V4014": "area_trab_principal",
    "V4028": "servidor_publico_estatutario",
    "V4029": "carteira_assinada",
    "V4032": "contribui_prev_trab_principal",
    "V4039": "horas_habituais_principal",
    "V4039C": "horas_efetivas_principal",
    "V4040": "tempo_nesse_trabalho",
    "V4047": "servidor_publico_secundario",
    "V4048": "carteira_assinada_secundario",
    "V4056": "horas_habituais_secundario",
    "V4056C": "horas_efetivas_secundario",
    "VD4013": "horas_habituais_todos_faixa",
    "VD4014": "horas_efetivas_todos_faixa",
    "VD4031": "horas_habituais_todos",
    "VD4032": "horas_efetivas_principal_h",
    "VD4033": "horas_efetivas_secundario_h",
    "VD4035": "horas_efetivas_todos",
    "VD4036": "horas_habituais_principal_faixa",
    "VD4037": "horas_efetivas_principal_faixa",
    "VD4015": "tipo_renda_principal",
    "VD4016": "renda_habitual_principal",
    "VD4017": "renda_efetiva_principal",
    "VD4018": "tipo_renda_todos",
    "VD4019": "renda_habitual_todos",
    "VD4020": "renda_efetiva_todos",
    "habitual": "renda_habitual_total",
    "efetivo": "renda_efetiva_total",
    "V403312": "valor_dinheiro_principal",
    "V403412": "valor_dinheiro_efetivo_principal",
    "V4071": "tomou_providencia_busca",
    "V4072": "metodo_busca_emprego_v1",
    "V4072A": "metodo_busca_emprego",
    "V4073": "gostaria_ter_trabalhado",
    "V4074": "motivo_nao_buscou_v1",
    "V4074A": "motivo_nao_buscou",
    "V4076": "tempo_desempregado",
    "V4077": "poderia_comecar_trabalhar",
    "V4078": "motivo_nao_trabalhou_v1",
    "V4078A": "motivo_nao_trabalhou",
    "VD4023": "motivo_fora_forca_trabalho",
    "VD4030": "motivo_fora_forca_trabalho2",
}


EDUCACAO_RENAME_MAP = {
    "V2003": "num_ordem",
    "V1016": "num_entrevista",
    "V1028": "peso",
    "posest": "estrato_pesquisa",
    "V1022": "zona",
    "V1023": "tipo_municipio",
    "V2001": "num_moradores",
    "V3001": "sabe_ler_escrever",
    "V3002": "frequenta_escola",
    "V3002A": "rede_escola",
    "V3003A": "curso_atual",
    "V3004": "duracao_curso_atual",
    "V3004A": "graduacao_tecnologica",
    "V3005A": "organizacao_curso_atual",
    "V3006": "ano_serie_atual",
    "V3006A": "etapa_fund_atual",
    "V3006B": "modalidade_curso_atual",
    "V3006C": "turno_curso",
    "V3007": "ja_concluiu_graduacao",
    "V3008": "frequentou_escola_antes",
    "V3009A": "curso_mais_elevado_anterior",
    "V3010": "duracao_curso_anterior",
    "V3010A": "graduacao_tec_anterior",
    "V3012": "concluiu_1a_serie_anterior",
    "V3013": "ultimo_ano_concluido_anterior",
    "V3014": "concluiu_curso_anterior",
    "V3017": "modalidade_curso_anterior",
    "V3019A": "frequenta_curso_tecnico",
    "V3020B": "tipo_curso_tecnico",
    "V3020C": "modalidade_curso_tecnico",
    "V3021A": "frequentou_curso_tecnico_antes",
    "V3023A": "concluiu_curso_tecnico_anterior",
    "V3024": "frequenta_pre_vestibular",
    "V3025": "frequenta_extensao_superior",
    "V3026": "frequenta_qualificacao_prof",
    "V3026A": "tipo_qualificacao_prof",
    "V3028": "frequentou_extensao_antes",
    "V3029": "frequentou_qualificacao_antes",
    "V3032": "concluiu_ultima_qualificacao",
    "V3033": "motivo_nao_frequenta_antes",
    "V3033A": "motivo_nao_frequenta_v2",
    "V3033B": "com_quem_fica_crianca",
    "V3034": "motivo_nao_frequenta_escola",
    "V3034A": "idade_parou_escola",
    "V3034B": "motivo_deixou_escola",
    "V3034C": "motivo_nao_frequenta_escola_atual",
}


INCOME_COLUMNS = [
    "renda_habitual_principal",
    "renda_efetiva_principal",
    "renda_habitual_todos",
    "renda_efetiva_todos",
    "renda_habitual_total",
    "renda_efetiva_total",
    "valor_dinheiro_principal",
    "valor_dinheiro_efetivo_principal",
]


HOURS_COLUMNS = [
    "horas_habituais_todos",
    "horas_efetivas_todos",
    "horas_habituais_principal",
    "horas_efetivas_principal",
    "horas_efetivas_principal_h",
    "horas_efetivas_secundario_h",
]


ANALYSIS_EDU_COLUMNS = [
    "id_domicilio",
    "num_ordem",
    "ano",
    "trimestre",
    "motivo_nao_frequenta_escola_atual",
    "motivo_nao_frequenta_escola",
    "motivo_deixou_escola",
    "frequenta_escola",
    "na_escola",
    "estudando_concurso",
    "frequenta_pre_vestibular",
    "esta_no_pre_vestibular",
    "frequenta_qualificacao_prof",
    "curso_atual",
    "modalidade_curso_atual",
]


TRANSITION_STATES = [
    "Fora da PEA",
    "Desocupado",
    "Conta-propria",
    "Setor Privado",
    "Setor Publico",
]


STATE_COLORS = {
    "Fora da PEA": "#888888",
    "Desocupado": "#E05C5C",
    "Conta-propria": "#F4A623",
    "Setor Privado": "#2B7BB9",
    "Setor Publico": "#3AAA5C",
}
